// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuyzeaupqhkbpklgdlcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eXplYXVwcWhrYnBrbGdkbGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTIwNzYsImV4cCI6MjA2NTQ4ODA3Nn0.eZEzNdLqk-GVjScMKcXfUzZKY8YglPa86y_bsNJkCCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);